### ISSUE TITLE
Example config is incorrect

### ISSUE THREAD

**Issue by Nevon** [webpack/imports-loader#10]
The example configuration file for using the imports loader is wrong:

```
// ./webpack.config.js

module.exports = {
    ...
    module: {
        loaders: [
            {
                test: require.resolve("some-module")
                loader: "imports?this=>window"
            }
        ]
};
```

The test property is according to the webpack documentation a condition that "may be a RegExp, a string containing the absolute path, a function(absPath): bool, or an array of one of these combined with 'and'.". `require.resolve`, on the other hand, returns a module id that is either a number or a string, depending on the environment.

**Comment by sokra** [comment]
`require.resolve` returns an absolute path to the file in node.js.
