### ISSUE TITLE
Import literal objects with multiple keys

### ISSUE THREAD

**Issue by vieron** [webpack/imports-loader#6]
If we can use `imports?config=>{foo:true}`, using `imports?config=>{foo:true,bar:false}` should also work. The inner comma is interpreted as a different value for the imports-loader and the result is invalid and unexpected JS code:

```
var config = {foo:true;
var bar:false}
```

Any workaround for this?

**Comment by sokra** [comment]
Technically you need to urlencode it: `imports?config=>{foo:true%2Cbar:false}`

**Comment by vieron** [comment]
I ended with `imports?config=>require('shims')`
